#!/bin/bash

jekyll serve --watch --host "127.0.0.1" --baseurl ""

border: 1px solid black;
    border-radius: 5px;
    color: white;
    background-color: black;
    font-size: 25px;
    font-family: Verdana;